version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    networks:
      - mynetwork

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate rest_api &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=social_db
      - DB_USER=postgres
      - DB_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: